/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ECS_ADMIN_BAKE_CONFIG_H
#define ECS_ADMIN_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <reflecs>
#include <reflecs.systems.admin>
#include <reflecs.systems.civetweb>

/* Headers of private dependencies */
#ifdef ECS_ADMIN_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if ECS_ADMIN_IMPL && defined _MSC_VER
#define ECS_ADMIN_EXPORT __declspec(dllexport)
#elif ECS_ADMIN_IMPL
#define ECS_ADMIN_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define ECS_ADMIN_EXPORT __declspec(dllimport)
#else
#define ECS_ADMIN_EXPORT
#endif

#endif

